type PdfLine = {
  text: string;
  size?: number;
  bold?: boolean;
  mono?: boolean;
  color?: [number, number, number];
  gapBefore?: number;
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function escapePdf(text: string) {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(text: string, size: number) {
  const maxChars = Math.max(24, Math.floor(CONTENT_WIDTH / (size * 0.52)));
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export function createSimplePdf(title: string, lines: PdfLine[]) {
  const pages: string[][] = [];
  let current: string[] = [];
  let y = PAGE_HEIGHT - MARGIN;

  function newPage() {
    if (current.length) pages.push(current);
    current = [];
    y = PAGE_HEIGHT - MARGIN;
  }

  function write(line: PdfLine) {
    const size = line.size ?? 10;
    y -= line.gapBefore ?? 0;
    const wrapped = wrapText(line.text || " ", size);
    for (const part of wrapped) {
      if (y < MARGIN + 28) newPage();
      const font = line.mono ? "F3" : line.bold ? "F2" : "F1";
      const [r, g, b] = line.color ?? [15, 23, 42];
      current.push(`${(r / 255).toFixed(3)} ${(g / 255).toFixed(3)} ${(b / 255).toFixed(3)} rg`);
      current.push(`BT /${font} ${size} Tf ${MARGIN} ${y.toFixed(2)} Td (${escapePdf(part)}) Tj ET`);
      y -= size + 4;
    }
  }

  write({ text: title, size: 22, bold: true, color: [2, 132, 199] });
  write({ text: "AgriVault export pack", size: 11, color: [71, 85, 105] });
  y -= 12;
  for (const line of lines) write(line);
  if (current.length) pages.push(current);

  const objects: string[] = [
    "",
    "",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>",
  ];
  const pageIds: number[] = [];
  for (const [index, commands] of pages.entries()) {
    const footer = [
      "0.392 0.455 0.545 rg",
      `BT /F1 8 Tf ${MARGIN} 28 Td (${escapePdf(`Generated by AgriVault - Page ${index + 1} of ${pages.length}`)}) Tj ET`,
    ];
    const stream = ["q", ...commands, ...footer, "Q"].join("\n");
    const streamId = objects.length + 1;
    objects.push(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    const pageId = objects.length + 1;
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R /F2 4 0 R /F3 5 0 R >> >> /Contents ${streamId} 0 R >>`);
    pageIds.push(pageId);
  }

  objects[0] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  const ordered = objects.map((body, i) => `${i + 1} 0 obj\n${body}\nendobj\n`);
  const header = "%PDF-1.4\n";
  let offset = Buffer.byteLength(header, "utf8");
  const offsets = [0];
  for (const object of ordered) {
    offsets.push(offset);
    offset += Buffer.byteLength(object, "utf8");
  }
  const xrefStart = offset;
  const xref = [
    `xref\n0 ${ordered.length + 1}`,
    "0000000000 65535 f ",
    ...offsets.slice(1).map((item) => `${String(item).padStart(10, "0")} 00000 n `),
    `trailer\n<< /Size ${ordered.length + 1} /Root 1 0 R >>`,
    `startxref\n${xrefStart}\n%%EOF`,
  ].join("\n");

  return Buffer.from(header + ordered.join("") + xref, "utf8");
}

export type { PdfLine };
